### ISSUE TITLE
this org needs a logo

### ISSUE THREAD

**Issue by stoeffel** [npm-scripts/meta#1]
^^

**Comment by hemanth** [comment]
Yes! :book:

**Comment by stoeffel** [comment]
any ideas?

**Comment by hemanth** [comment]
Yellow bg, with `npm-script`?

**Comment by stoeffel** [comment]
I would go with red and white.

**Comment by hemanth** [comment]
:+1:

**Comment by jamiebuilds** [comment]
![scripts](https://cloud.githubusercontent.com/assets/952783/8645953/cf17bcc4-2900-11e5-89b2-b2501692c6eb.png)

**Comment by hemanth** [comment]
/me passes some :cookie: to @thejameskyle :+1:

**Comment by stoeffel** [comment]
@thejameskyle nice!

**Comment by jamiebuilds** [comment]
uploaded

**Comment by hemanth** [comment]
:+1:
