### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by stoeffel** [npm-scripts/meta#2]
How about creating a cli to search for scripts and adding them to `package.json`?
We would have to maintain the scripts in a json file and build the current md from it (we could use [doxie](https://github.com/stoeffel/react-material-card) for that)

Example json

``` json
{
  "minor-release": {
    "description": "Bumps the version and releases the package",
    "script": "npm version patch && npm publish && git push --follow-tags",
    "keywords": ["npm", "version"]
  },
  ...
}
```

``` bash
$ npm-scripts search version
```

**Comment by hemanth** [comment]
A big :+1:

**Comment by jamiebuilds** [comment]
https://github.com/thejameskyle/npm-scripts

**Comment by hemanth** [comment]
@thejameskyle nice, would you like to transfer that module to this org ;) ?

**Comment by stoeffel** [comment]
Nice. would be cool if you could transfer this. and maybe use the
scripts.json (we could publish the scripts repo to npm and the cli could
depend on it) from our main repo.

**Comment by jamiebuilds** [comment]
I was going to just make a PR on the existing repo with the contents of that repo

**Comment by hemanth** [comment]
It's easier to transfer :)

**Comment by jamiebuilds** [comment]
but then you lose git history

**Comment by stoeffel** [comment]
I would go with a pr. we can separate it in a different repo
later(scripts-cli)

**Comment by stoeffel** [comment]
How about if the cli-tool would fetch the data from [remote](https://raw.githubusercontent.com/npm-scripts/scripts/master/scripts.json) (and fall back to a local cached copy if no connection) so users don't have to update every time we add a new script? //cc @npm-scripts/owners
